git:
  submodules: true
language: scala
sudo: required
cache:
  apt: true
  directories:
    $HOME/.ivy2
    ivlsim/iverilog
    verisim/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - device-tree-compiler
      - libusb-1.0-0-dev
      - python-pexpect


# These branches are the only ones that
# will build when "build branch updates"
# is set in settings (branches which PR against
# them are still built). With this set,
# the above blacklist is not useful.
# Adding this allows us to keep "Build Branch Updates"
# set to 'ON'.

branches:
  only:
  - master

jobs:
  include:
#    - stage: prepare cache-riscv-tools
#      script:
#        - travis_wait 120 make tools -C regression SUITE=none
#      before_install:
#        - export CXX=g++-4.8 CC=gcc-4.8
#      before_cache:
#        - ls -t regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
    - stage: prepare cache-verilator
      script:
        - travis_wait 120 make verilator -C verisim
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8
    - stage: prepare cache-ivlsim
      script:
        - travis_wait 120 make iverilog -C ivlsim
      before_install:
        - export CXX=g++-4.8 CC=gcc-4.8
    - &test
      stage: Test
      script:
        - travis_wait 100 make -f Makefile.examplefpga verilog
    - <<: *test
      script:
        - travis_wait 80 make PROJECT=examplefpga -C verisim
    - <<: *test
      script:
        - travis_wait 80 make PROJECT=example -C verisim
